name: event_loc
version: 1.0.0+1
publish_to: none
description: organisation d’évènement entre membre
environment: 
  sdk: '>=2.15.0-116.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  getxfire: 0.3.1
  safetynet_attestation: 0.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

