// Autogenerated from Pigeon (v1.0.8), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package io.flutter.plugins;

import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class User {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class UserModel {
    private String id;
    public String getId() { return id; }
    public void setId(String setterArg) { this.id = setterArg; }

    private String firstname;
    public String getFirstname() { return firstname; }
    public void setFirstname(String setterArg) { this.firstname = setterArg; }

    private String lastname;
    public String getLastname() { return lastname; }
    public void setLastname(String setterArg) { this.lastname = setterArg; }

    private String email;
    public String getEmail() { return email; }
    public void setEmail(String setterArg) { this.email = setterArg; }

    private String location;
    public String getLocation() { return location; }
    public void setLocation(String setterArg) { this.location = setterArg; }

    private String phone;
    public String getPhone() { return phone; }
    public void setPhone(String setterArg) { this.phone = setterArg; }

    private String avatarUrl;
    public String getAvatarUrl() { return avatarUrl; }
    public void setAvatarUrl(String setterArg) { this.avatarUrl = setterArg; }

    private String state;
    public String getState() { return state; }
    public void setState(String setterArg) { this.state = setterArg; }

    private String type;
    public String getType() { return type; }
    public void setType(String setterArg) { this.type = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("id", id);
      toMapResult.put("firstname", firstname);
      toMapResult.put("lastname", lastname);
      toMapResult.put("email", email);
      toMapResult.put("location", location);
      toMapResult.put("phone", phone);
      toMapResult.put("avatarUrl", avatarUrl);
      toMapResult.put("state", state);
      toMapResult.put("type", type);
      return toMapResult;
    }
    static UserModel fromMap(Map<String, Object> map) {
      UserModel fromMapResult = new UserModel();
      Object id = map.get("id");
      fromMapResult.id = (String)id;
      Object firstname = map.get("firstname");
      fromMapResult.firstname = (String)firstname;
      Object lastname = map.get("lastname");
      fromMapResult.lastname = (String)lastname;
      Object email = map.get("email");
      fromMapResult.email = (String)email;
      Object location = map.get("location");
      fromMapResult.location = (String)location;
      Object phone = map.get("phone");
      fromMapResult.phone = (String)phone;
      Object avatarUrl = map.get("avatarUrl");
      fromMapResult.avatarUrl = (String)avatarUrl;
      Object state = map.get("state");
      fromMapResult.state = (String)state;
      Object type = map.get("type");
      fromMapResult.type = (String)type;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class Reply {
    private UserModel userModel;
    public UserModel getUserModel() { return userModel; }
    public void setUserModel(UserModel setterArg) { this.userModel = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("userModel", (userModel == null) ? null : userModel.toMap());
      return toMapResult;
    }
    static Reply fromMap(Map<String, Object> map) {
      Reply fromMapResult = new Reply();
      Object userModel = map.get("userModel");
      fromMapResult.userModel = UserModel.fromMap((Map)userModel);
      return fromMapResult;
    }
  }
  private static class UserModelApiCodec extends StandardMessageCodec {
    public static final UserModelApiCodec INSTANCE = new UserModelApiCodec();
    private UserModelApiCodec() {}
    @Override
    protected Object readValueOfType(byte type, ByteBuffer buffer) {
      switch (type) {
        case (byte)128:         
          return Reply.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)129:         
          return UserModel.fromMap((Map<String, Object>) readValue(buffer));
        
        default:        
          return super.readValueOfType(type, buffer);
        
      }
    }
    @Override
    protected void writeValue(ByteArrayOutputStream stream, Object value)     {
      if (value instanceof Reply) {
        stream.write(128);
        writeValue(stream, ((Reply) value).toMap());
      } else 
      if (value instanceof UserModel) {
        stream.write(129);
        writeValue(stream, ((UserModel) value).toMap());
      } else 
{
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated class from Pigeon that represents Flutter messages that can be called from Java.*/
  public static class UserModelApi {
    private final BinaryMessenger binaryMessenger;
    public UserModelApi(BinaryMessenger argBinaryMessenger){
      this.binaryMessenger = argBinaryMessenger;
    }
    public interface Reply<T> {
      void reply(T reply);
    }
    static MessageCodec<Object> getCodec() {
      return UserModelApiCodec.INSTANCE;
    }

    public void onReply(Reply replyArg, Reply<Void> callback) {
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.UserModelApi.onReply", getCodec());
      channel.send(new ArrayList<Object>(Arrays.asList(replyArg)), channelReply -> {
        callback.reply(null);
      });
    }
  }
  private static Map<String, Object> wrapError(Throwable exception) {
    Map<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", null);
    return errorMap;
  }
}
