// Autogenerated from Pigeon (v1.0.9), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class BookModel;
@class Thumbnail;

@interface BookModel : NSObject
@property(nonatomic, copy, nullable) NSString * title;
@property(nonatomic, copy, nullable) NSString * urlImage;
@property(nonatomic, copy, nullable) NSString * author;
@property(nonatomic, copy, nullable) NSString * summary;
@property(nonatomic, copy, nullable) NSString * publishDate;
@property(nonatomic, strong, nullable) NSNumber * pageCount;
@property(nonatomic, strong, nullable) Thumbnail * thumbnail;
@end

@interface Thumbnail : NSObject
@property(nonatomic, copy, nullable) NSString * url;
@end

/// The codec used by FlutterBookApi.
NSObject<FlutterMessageCodec> *FlutterBookApiGetCodec(void);

@interface FlutterBookApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)displayBookDetailsBookModel:(BookModel *)bookModel completion:(void(^)(NSError *_Nullable))completion;
@end
/// The codec used by BookModelApi.
NSObject<FlutterMessageCodec> *BookModelApiGetCodec(void);

@protocol BookModelApi
- (nullable NSArray<BookModel *> *)searchKeyword:(NSString *)keyword error:(FlutterError *_Nullable *_Nonnull)error;
- (void)cancelWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)finishEditingBookBookModel:(BookModel *)bookModel error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void BookModelApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BookModelApi> *_Nullable api);

NS_ASSUME_NONNULL_END
