// Autogenerated from Pigeon (v1.0.8), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class BookModel;

@interface BookModel : NSObject
@property(nonatomic, copy, nullable) NSString * title;
@property(nonatomic, copy, nullable) NSString * urlImage;
@end

/// The codec used by BookModelApi.
NSObject<FlutterMessageCodec> *BookModelApiGetCodec(void);

@protocol BookModelApi
- (nullable NSArray<BookModel *> *)searchKeyword:(NSString *)keyword error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void BookModelApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BookModelApi> *_Nullable api);

NS_ASSUME_NONNULL_END
