// Autogenerated from Pigeon (v1.0.9), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class UserModel;
@class AvatarUrl;

@interface UserModel : NSObject
@property(nonatomic, copy, nullable) NSString * id;
@property(nonatomic, copy, nullable) NSString * firstname;
@property(nonatomic, copy, nullable) NSString * lastname;
@property(nonatomic, copy, nullable) NSString * email;
@property(nonatomic, copy, nullable) NSString * location;
@property(nonatomic, copy, nullable) NSString * phone;
@property(nonatomic, strong, nullable) AvatarUrl * avatarUrl;
@property(nonatomic, copy, nullable) NSString * state;
@property(nonatomic, copy, nullable) NSString * type;
@end

@interface AvatarUrl : NSObject
@property(nonatomic, copy, nullable) NSString * url;
@end

/// The codec used by FlutterUserApi.
NSObject<FlutterMessageCodec> *FlutterUserApiGetCodec(void);

@interface FlutterUserApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)displayUserDetailsUserModel:(UserModel *)userModel completion:(void(^)(NSError *_Nullable))completion;
@end
/// The codec used by UserModelApi.
NSObject<FlutterMessageCodec> *UserModelApiGetCodec(void);

@protocol UserModelApi
- (nullable NSArray<UserModel *> *)getUserKeyword:(NSString *)keyword error:(FlutterError *_Nullable *_Nonnull)error;
- (void)cancelWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)finishEditingProfileUserModel:(UserModel *)userModel error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void UserModelApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<UserModelApi> *_Nullable api);

NS_ASSUME_NONNULL_END
