// Autogenerated from Pigeon (v1.0.8), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class UserModel;
@class Reply;

@interface UserModel : NSObject
@property(nonatomic, copy, nullable) NSString * id;
@property(nonatomic, copy, nullable) NSString * firstname;
@property(nonatomic, copy, nullable) NSString * lastname;
@property(nonatomic, copy, nullable) NSString * email;
@property(nonatomic, copy, nullable) NSString * location;
@property(nonatomic, copy, nullable) NSString * phone;
@property(nonatomic, copy, nullable) NSString * avatarUrl;
@property(nonatomic, copy, nullable) NSString * state;
@property(nonatomic, copy, nullable) NSString * type;
@end

@interface Reply : NSObject
@property(nonatomic, strong, nullable) UserModel * userModel;
@end

/// The codec used by UserModelApi.
NSObject<FlutterMessageCodec> *UserModelApiGetCodec(void);

@interface UserModelApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onReplyReply:(Reply *)reply completion:(void(^)(NSError *_Nullable))completion;
@end
NS_ASSUME_NONNULL_END
