// Autogenerated from Pigeon (v1.0.9), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name
// @dart = 2.12
import 'dart:async';
import 'dart:typed_data' show Uint8List, Int32List, Int64List, Float64List;

import 'package:flutter/foundation.dart' show WriteBuffer, ReadBuffer;
import 'package:flutter/services.dart';

class BookModel {
  String? title;
  String? urlImage;
  String? author;
  String? summary;
  String? publishDate;
  int? pageCount;
  Thumbnail? thumbnail;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['title'] = title;
    pigeonMap['urlImage'] = urlImage;
    pigeonMap['author'] = author;
    pigeonMap['summary'] = summary;
    pigeonMap['publishDate'] = publishDate;
    pigeonMap['pageCount'] = pageCount;
    pigeonMap['thumbnail'] = thumbnail == null ? null : thumbnail!.encode();
    return pigeonMap;
  }

  static BookModel decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return BookModel()
      ..title = pigeonMap['title'] as String?
      ..urlImage = pigeonMap['urlImage'] as String?
      ..author = pigeonMap['author'] as String?
      ..summary = pigeonMap['summary'] as String?
      ..publishDate = pigeonMap['publishDate'] as String?
      ..pageCount = pigeonMap['pageCount'] as int?
      ..thumbnail = pigeonMap['thumbnail'] != null
          ? Thumbnail.decode(pigeonMap['thumbnail']!)
          : null;
  }
}

class Thumbnail {
  String? url;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['url'] = url;
    return pigeonMap;
  }

  static Thumbnail decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return Thumbnail()
      ..url = pigeonMap['url'] as String?;
  }
}

class _FlutterBookApiCodec extends StandardMessageCodec {
  const _FlutterBookApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is BookModel) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else 
    if (value is Thumbnail) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else 
{
      super.writeValue(buffer, value);
    }
  }
  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return BookModel.decode(readValue(buffer)!);
      
      case 129:       
        return Thumbnail.decode(readValue(buffer)!);
      
      default:      
        return super.readValueOfType(type, buffer);
      
    }
  }
}
abstract class FlutterBookApi {
  static const MessageCodec<Object?> codec = _FlutterBookApiCodec();

  void displayBookDetails(BookModel bookModel);
  static void setup(FlutterBookApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.FlutterBookApi.displayBookDetails', codec, binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null, 'Argument for dev.flutter.pigeon.FlutterBookApi.displayBookDetails was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BookModel? arg_bookModel = (args[0] as BookModel?);
          assert(arg_bookModel != null, 'Argument for dev.flutter.pigeon.FlutterBookApi.displayBookDetails was null, expected non-null BookModel.');
          api.displayBookDetails(arg_bookModel!);
          return;
        });
      }
    }
  }
}

class _BookModelApiCodec extends StandardMessageCodec {
  const _BookModelApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is BookModel) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else 
    if (value is BookModel) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else 
    if (value is Thumbnail) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else 
{
      super.writeValue(buffer, value);
    }
  }
  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return BookModel.decode(readValue(buffer)!);
      
      case 129:       
        return BookModel.decode(readValue(buffer)!);
      
      case 130:       
        return Thumbnail.decode(readValue(buffer)!);
      
      default:      
        return super.readValueOfType(type, buffer);
      
    }
  }
}

class BookModelApi {
  /// Constructor for [BookModelApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BookModelApi({BinaryMessenger? binaryMessenger}) : _binaryMessenger = binaryMessenger;

  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _BookModelApiCodec();

  Future<List<BookModel?>> search(String arg_keyword) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.BookModelApi.search', codec, binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap =
        await channel.send(<Object>[arg_keyword]) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null,
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error = (replyMap['error'] as Map<Object?, Object?>?)!;
      throw PlatformException(
        code: (error['code'] as String?)!,
        message: error['message'] as String?,
        details: error['details'],
      );
    } else {
      return (replyMap['result'] as List<Object?>?)!.cast<BookModel?>();
    }
  }

  Future<void> cancel() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.BookModelApi.cancel', codec, binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap =
        await channel.send(null) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null,
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error = (replyMap['error'] as Map<Object?, Object?>?)!;
      throw PlatformException(
        code: (error['code'] as String?)!,
        message: error['message'] as String?,
        details: error['details'],
      );
    } else {
      return;
    }
  }

  Future<void> finishEditingBook(BookModel arg_bookModel) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.BookModelApi.finishEditingBook', codec, binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap =
        await channel.send(<Object>[arg_bookModel]) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null,
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error = (replyMap['error'] as Map<Object?, Object?>?)!;
      throw PlatformException(
        code: (error['code'] as String?)!,
        message: error['message'] as String?,
        details: error['details'],
      );
    } else {
      return;
    }
  }
}
